### ISSUE TITLE
Make package public

### ISSUE THREAD

**Issue by xddq** [sinclairzx81/typebox-codegen#10]
## Motivation:
- I think the idea is cool and I guess we could find more minds working on it
- Packages depending on it like [@sinclair/typebox](https://github.com/sinclairzx81/typebox), [typebox-workbench](https://github.com/sinclairzx81/typebox-workbench) and [ts2typebox](https://github.com/xddq/ts2typebox) have a single source of truth and don't have to manually update the source code changes.

Do you have any strong points for keeping it private?

## How to do it
- We have to communicate that this is "experimental and work in progress" in the first few lines of the readme.
- Ensure that the relevant functions are exported (I have no clue about this yet) but I it won't be to hard.

**Comment by sinclairzx81** [comment]
@xddq Heya,

Have published the first revisions to NPM (at last)

```
npm install @sinclair/typebox-codegen
```
Usage
```typescript
import * as Codegen from '@sinclair/typebox-codegen'

const C = Codegen.TypeScriptToTypeBox.Generate(`
  type T = { x: number, y: number, z: number }
`)

console.log(Codegen.Formatter.Format(C))
```
Will close off this issue for now :)
Cheers
S
