### ISSUE TITLE
Type.Optional case

### ISSUE THREAD

**Issue by alexey13** [sinclairzx81/typebox-codegen#27]
Hey, hey again!
Have another one.
Check it, please:
Thanks!

```ts
const Model = {
  exports: new Map(),
  types: [Type.Object({ a: Type.Optional(Type.String()) }, { $id: 'Test' })],
};
const typescript = Codegen.Formatter.Format(
  Codegen.ModelToTypeScript.GenerateType(Model, 'Test'),
);
// typescript
`export type Test = {
  a: string
}`
// should be
`export type Test = {
  a?: string
}`
```

**Comment by sinclairzx81** [comment]
@alexey13 Heya, thanks for reporting

Fixed on 0.9.7 as well as the workbench https://sinclairzx81.github.io/typebox-workbench

For additional issues, it can be helpful to repro on the workbench (you can Ctrl+S and copy and paste the URL into the issue)

Cheers!
