### ISSUE TITLE
Block-scoped variable 'T' used before its declaration.ts

### ISSUE THREAD

**Issue by liyofx** [sinclairzx81/typebox-codegen#31]
```
  const Code = `
  export type R = {
      a: number,
      t: T
  }
  export type T = {
      z: number,
      r: R
  }
  `
  console.log(Codegen.TypeScriptToTypeBox.Generate(Code))
```
Block-scoped variable 'T' used before its declaration.ts
```
import { Type, Static } from '@sinclair/typebox'


export type R = Static<typeof R>
export const R = Type.Object({
a: Type.Number(),
t: T
})

export type T = Static<typeof T>
export const T = Type.Object({
z: Type.Number(),
r: R
})
```

**Comment by sinclairzx81** [comment]
@liyofx Hi, Thanks for reporting (and apologies for the extended delay in reply)

So, TypeBox doesn't support direct mutual recursive types. But they can be expressed in the following (rather verbose) way.

```typescript
import { Type, TSchema, Static } from '@sinclair/typebox'

// Mutual Recursive Template
const __R = <T extends TSchema>(reference: T) => Type.Object({
  a: Type.Number(),
  t: reference
})

const __T = <T extends TSchema>(reference: T) => Type.Object({
  z: Type.Number(),
  r: reference
})

// ....

// Mutual Recursive Types
const R = Type.Recursive((This) => __R(__T(This)))
const T = Type.Recursive((This) => __T(__R(This)))

type R = Static<typeof R>
type T = Static<typeof T>
```
In terms of code generation, I'm going to hold off on supporting mutual recursive types until such time as TypeBox provides a moderately tenable API for them. Additionally, there are also some challenges deriving mutual recursive-ness via the TS Compiler API, as well as producing generation targets for each library (all of which requires a fair amount of research, time and effort to achieve)

For now, mutual recursive types are in the considered "out of scope", but will report back on this issue if there are updates to TB to support these types (such that there's a tenable emit target for them)

Will close off for now
Cheers
S
