### ISSUE TITLE
Yup schema is not fully generated if types are not in the right order

### ISSUE THREAD

**Issue by stefann01** [sinclairzx81/typebox-codegen#34]
So if I have something like this the full schema is not generated: 
```
type Person = {
  age: number;
  address: Address;
}

type Address = {
  street: string;
}
```

Just the schema for the `Address` is generated.

**Comment by sinclairzx81** [comment]
@stefann01 Hi,

Currently, this project requires you specify types in dependent order (as no topological sorting occurs). Note that TS types can be defined in any order, but at runtime types do need to be defined before use. 

At this stage, default topo sort for the transforms is currently deemed "out of scope" as there are cases where no sorting is possible (i.e. mutual recursive types) and haven't decided how I want to proceed. The current recommendation is just to ensure your definitions are ordered in sequence of dependence. 

Hope this helps!
S

**Comment by sinclairzx81** [comment]
@stefann01 Heya,

Will close this one off for now as order dependence (or topo sorting types) is currently in the "too hard" basket (as it would be challenging to work this for all the code generators). I may revisit in future tho (if TB introduces support for mutual recursive types (which are partially related to this)). Will ping this thread if there are any changes to the current emit order.

Cheers!
S
