### ISSUE TITLE
Enum generation

### ISSUE THREAD

**Issue by stefann01** [sinclairzx81/typebox-codegen#36]
Is is possible to export enums as yup in this way?

Suppose we have this input: 
```
export enum WeekDays  {
    Monday="Monday",
    Tuesday="Tuesday"
}
```
The actual generation is: 

```
import y from 'yup'

export type WeekDays = y.InferType<typeof WeekDays>
export const WeekDays = y
  .mixed()
  .oneOf([
    y.mixed((value): value is 'Monday' => value === 'Monday').required(),
    y.mixed((value): value is 'Tuesday' => value === 'Tuesday').required()
  ])
  .required()
```

Can it be exported like this? 

```
export type WeekDays = y.InferType<typeof WeekDays>
export const WeekDays = y
  .string()
  .oneOf(['Monday', 'Tuesday'])
  .required()
```

**Comment by sinclairzx81** [comment]
@stefann01 Hi

It should be possible to implement a special case transform that generated the `.oneOf(['Monday', 'Tuesday'])` if all union members were literal string (or number) types. I note that currently, the Yup transform does generate fairly arcane code to represent string literal values. There may be better ways to represent types in Yup across the board, but unfortunately, I'm not a Yup user (the current transforms are based on the best approximations I could find)

Would you be interested in submitting a PR for this? The relevant code can be found... https://github.com/sinclairzx81/typebox-workbench/blob/main/src/codegen/model/model-to-yup.ts#L149-L151. Note that updates to this project are made through the workbench project first (as that library provides an interactive scripting environment to test). If you are interested, just submit a PR there and would be happy to review.

Cheers!
S

**Comment by stefann01** [comment]
@sinclairzx81 Hi

I opened a PR here: https://github.com/sinclairzx81/typebox-workbench/pull/12 Let me know your thoughts

**Comment by sinclairzx81** [comment]
@stefann01 Hey, thanks for the PR!

Have merged this in and applied a quick update just to generalize for "Union Literal" types (where all enums are Union Literal, and "some" Unions are as well). This seems like a good way to reduce on some of the output for unions that fit the criteria (as below)



```typescript
// ...

export type A = 'X' | 'Y'

// export type A = y.InferType<typeof A>
// export const A = y.mixed().oneOf(['X', 'Y']).required()

// ...

export enum B {
  X = 'X',
  Y = 'Y'
}

// export type B = y.InferType<typeof B>
// export const B = y.mixed().oneOf(['X', 'Y']).required()

// ...

export type C = 'X' | 'Y' | { x: number } // noting that `{ x: number }` does not fit the criteria for Union Literal

// export type C = y.InferType<typeof C>
// export const C = y
//   .mixed()
//   .oneOf([
//     y.mixed((value): value is 'X' => value === 'X').required(),
//     y.mixed((value): value is 'Y' => value === 'Y').required(),
//     y.object({
//       x: y.number().required()
//     })
//   ])
//   .required()
```
There may be potential to reduce `C` to `string` values also (which would need to be handled on the `Literal` transform), but have published the above on @sinclair/typebox-codegen@0.9.8.

Thanks again for the PR!
Cheers
S

**Comment by stefann01** [comment]
I will take some time soon to see how that would be possible for C. 
Thank you!

**Comment by sinclairzx81** [comment]
@stefann01 Hi,

I think this issue should be resolved. Will close off for now but if you spot any issues with the current Yup output, feel free to ping on this thread.

All the best!
S
