### ISSUE TITLE
Union and Intersect types incorrect generation 

### ISSUE THREAD

**Issue by Barrokgl** [sinclairzx81/typebox-codegen#37]
Hi! 
I've encountered a problem while I was trying to generate types from typebox descriptions. Here is the code example:
```typescript
import { Type } from '@sinclair/typebox';
import * as Codegen from '@sinclair/typebox-codegen';

const A1 = Type.Object(
    {
        first: Type.String(),
    },
    { title: 'A1' },
);

const A2 = Type.Object(
    {
        first: Type.String(),
        second: Type.Number(),
    },
    { title: 'A2' },
);

const C = Type.Union([A1, A2], { title: 'C' });

const B1 = Type.Object(
    {
        third: Type.String(),
    },
    { title: 'B1' },
);

const B2 = Type.Object(
    {
        third: Type.String(),
        forth: Type.Number(),
    },
    { title: 'B2' },
);

const D = Type.Union([B1, B2], { title: 'D' });

const E = Type.Intersect([C, D], { title: 'E', $id: 'E' });

const model: Codegen.TypeBoxModel = {
    exports: new Map(),
    types: [E],
};

const code = Codegen.ModelToTypeScript.GenerateType(model, 'E');

```

And what I expected as an output is:

```typescript
export type E = (
    | {
          first: string;
      }
    | {
          first: string;
          second: number;
      }
) &
    (
        | {
              third: string;
          }
        | {
              third: string;
              forth: number;
          }
    );
```

Instead, I'm getting this:
```
export type E =
    | {
          first: string;
      }
    | {
          first: string;
          second: number;
      } & {
          third: string;
      }
    | {
          third: string;
          forth: number;
      };
```

Looks to me like it caused by lack of wrapping parens here https://github.com/sinclairzx81/typebox-codegen/blob/main/src/model/model-to-typescript.ts#L131

Thank you!

**Comment by sinclairzx81** [comment]
@Barrokgl Hi, thanks for reporting (and sorry for the delay, this project a fairly low bandwidth atm)

Have pushed a fix for this on 0.9.13. The enclosing parens have been applied to both Union and Intersect so should be yielding the correct type. You can test on https://sinclairzx81.github.io/typebox-workbench/

Will leave this issue open for a few days to give you some time to test. 
Thanks again
S

**Comment by sinclairzx81** [comment]
@Barrokgl Heya, 

Going to close off this issue as things should be working alright here. Again, thanks for reporting :)

Cheers!
S

**Comment by Barrokgl** [comment]
@sinclairzx81 thanks a lot!
