### ISSUE TITLE
[TypeScriptToTypeBox] Labeled tuple support

### ISSUE THREAD

**Issue by ilyhalight** [sinclairzx81/typebox-codegen#39]
Typescript has [labeled tuple support](https://devblogs.microsoft.com/typescript/announcing-typescript-4-0/#labeled-tuple-elements), but when generating code through typebox-codegen, it turns into an invalid tuple. How about adding the same support to typebox-codegen? For example, as I wrote in the expected code (turning typescript labeled tuple into a regular Type.Tuple)

Typescript code:
```
export type NewLocation = [lat: number, long: number]
```

Typebox [generated code](https://sinclairzx81.github.io/typebox-workbench/?share=Ly8gRWRpdCBUeXBlU2NyaXB0IFR5cGVzIEhlcmUuIFVzZSBDdHJsICsgUyB0byBTaGFyZQoKZXhwb3J0IHR5cGUgTmV3TG9jYXRpb24gPSBbbGF0OiBudW1iZXIsIGxvbmc6IG51bWJlcl0K) (invalid):
```
import { Type, Static } from '@sinclair/typebox'

export type NewLocation = Static<typeof NewLocation>
export const NewLocation = Type.Tuple([,])
```

Typebox expected valid code:
```
import { Type, Static } from '@sinclair/typebox'

export type NewLocation = Static<typeof NewLocation>
export const NewLocation = Type.Tuple([Type.Number(), Type.Number()])
```

**Comment by sinclairzx81** [comment]
@ilyhalight Hi, Good spotting.

Have pushed a fixed this to the Workbench, and applied the same update to https://github.com/sinclairzx81/typebox-codegen on 0.9.12. You should be able to visit the workbench now, but just be sure you clear out your browser cache (specifically LocalStorage) if you see the old output.

Thanks for reporting!
S
