### ISSUE TITLE
Is JsonSchema really supported

### ISSUE THREAD

**Issue by twarogowski** [sinclairzx81/typebox-codegen#41]
Hi,,
i tried to generate JsonSchema from my model is nuch way:

```
const Model: Codegen.TypeBoxModel = {
  types: [schema], 
};
let schemaString = Codegen.ModelToJsonSchema.Generate(Model);
```

but what I get is not valid JSON, instead it looks like this:

```
export const undefined = {
  type: 'object',
  properties: {
    types: {
      type: 'array',
      items: {
        $id: 'Type',
        type: 'object',
        properties: {
          name: {
            minLength: 3,
            maxLength: 200,
            type: 'string'
          },
          description: {
            type: 'string'
          },
          properties: {
            type: 'array',
            items: {
              $id: 'Property',
              type: 'object',
              properties: {
                name: {
                  minLength: 3,
                  maxLength: 200,
                  type: 'string'
                },
                optional: {
                  default: false,
                  type: 'boolean'
                }
              },
              required: ['name', 'optional']
            }
          }
        },
        required: ['name', 'properties']
      }
    }
  },
  required: ['types']
}
```
how should I changeit to get proper Json (Schema) file?

**Comment by sinclairzx81** [comment]
@twarogowski Hello,

> Is JsonSchema really supported

Yes, it's supported (albeit the Json Schema code generation output is embeds it in a JavaScript variable). However you don't actually need to use code generation if the source type is a TypeBox type. TypeBox types are already Json Schema, so if you just want a plain Json Schema string, use JSON.stringify on the schema.

```typescript
const schemaString = JSON.stringify(schema, null, 2) // this is raw json schema
```

This project provides the Json Schema generator primarily for TS -> TB  -> Json Schema code transformation which is used on the following project (where it can be useful to generate Json Schema directly from TypeScript types)

https://sinclairzx81.github.io/typebox-workbench

But outside of this, you shouldn't need to use code generation to produce Json Schema if you're using TypeBox, just stringify the TypeBox type.

Hope this helps
S

**Comment by sinclairzx81** [comment]
@twarogowski Hiya,

Going to close off this issue as you should be able get the raw json schema from the typebox type without code generation. However if you are using code generation, to fix the `undefined` variable name, give the schema a `$id` as the generator uses the id as the variable name.

If you have any question on the above, feel free to ping on this thread.
Cheers
S

**Comment by twarogowski** [comment]
Thank you,

You helped me a lot!

Cheers,
Łukasz
