### ISSUE TITLE
typescript to typebox - Map<> not implemented yet

### ISSUE THREAD

**Issue by xddq** [sinclairzx81/typebox-codegen#8]
I am currently writing tests for the "typescript to typebox" part of this package. I tried writing a test with "Map<string, number>" with resulted in T.Never(). I therefore think this is not implemented yet.

## How to reproduce
- adapt example file to contain:
```
const Code = `
  module Tuples {
    export type T1 = Map<string,number>
  }
`
// ----------------------------------------------------------------------------
// Typescript Base
// ----------------------------------------------------------------------------
Print('Typescript code (base)', Code)
// ----------------------------------------------------------------------------
// Immediate Transform
// ----------------------------------------------------------------------------
Print('TypeScript To TypeBox', Codegen.TypeScriptToTypeBox.Generate(Code))

```
- `yarn start`
- result: 
![grafik](https://user-images.githubusercontent.com/44843935/233821362-c54cc82b-2bf8-4a09-af5e-6490ab4526e1.png)

**Comment by sinclairzx81** [comment]
@xddq Heya, 

Might close off this one for now. At the moment, there's not really target data type for `Map` and `Set`, and even tho TB could technically support them via `TUnsafe`, I'm going to limit things to built in types only (at least for now) as the current standard type set acts as a minimal mvp to get transformations in place for the other validators (and document the things that can't be mapped)

Will pick this up at a later time.
Cheers!
S
